server:
  port: 8761
spring:
  application:
    name: registry
security:
  basic:
    enabled: false
  user:
    name: jls
    password: 111111
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/